name: jgalaxian
version: "0.0.1"
summary: A Java Galaxian clone
description: |
  JGalaxian is a Java-based Galaxian clone.
confinement: strict
grade: stable
base: core18

apps:
  jgalaxian:
    command: bash -c "${SNAP}/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}/bin/java -version ; ${SNAP}/usr/lib/jvm/java-8-openjdk-${SNAP_ARCH}/bin/java -Djava.util.prefs.userRoot=\"$SNAP_USER_DATA\" -jar $SNAP/jar/jgalaxian-1.0-SNAPSHOT.jar $*"
    environment:
      # pulseaudio
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      # Needed for fontconfig
      XDG_DATA_HOME: ${SNAP}/usr/share
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/config.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
    plugs: [x11,pulseaudio]

parts:
  jgalaxian:
    plugin: maven
    source-type: local
    source: .
    build-packages:
      - openjdk-8-jdk
    stage-packages:
      - openjdk-8-jdk
      - libpulse0

