name: jgalaxian
version: "0.0.1"
summary: A Java Galaxian clone
description: |
  JGalaxian is a Java-based Galaxian clone.
confinement: strict
grade: stable
base: core18

apps:
  jgalaxian:
    command: bash -c "echo LD_LIBRARY_PATH=$LD_LIBRARY_PATH ; java -version ; java -Djava.util.prefs.userRoot=\"$SNAP_USER_DATA\" -jar $SNAP/jar/jgalaxian-1.0-SNAPSHOT.jar $@"
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
      # Needed for fontconfig
      XDG_DATA_HOME: $SNAP/usr/share
      FONTCONFIG_PATH: $SNAP/etc/fonts/config.d
      FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
    plugs: [x11,pulseaudio]

parts:
  jgalaxian:
    plugin: maven
    source-type: local
    source: .
    build-packages:
      - openjdk-11-jdk
    stage-packages:
      - libpulse0
      - libpulse-java

